version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    ports:
      - "5050:5000"
    networks:
      - bucket-viewer-network
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 500M
        reservations:
          cpus: '0.3'
          memory: 300M
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:80"
    depends_on:
      - backend  
    networks:
      - bucket-viewer-network
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 800M
        reservations:
          cpus: '0.3'
          memory: 400M

volumes:
  node_modules:

networks:
  bucket-viewer-network:
    driver: bridge