version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production  # Changed to production for lower memory footprint
    ports:
      - "5050:5000"
    networks:
      - bucket-viewer-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 150M
        reservations:
          cpus: '0.2'
          memory: 100M
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:80"
    depends_on:
      - backend  
    networks:
      - bucket-viewer-network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 200M
        reservations:
          cpus: '0.2'
          memory: 150M
    restart: unless-stopped

volumes:
  node_modules:

networks:
  bucket-viewer-network:
    driver: bridge